import json
import os
from datetime import datetime
from pathlib import Path

from rich.table import Table

from ui.tui import _sum_program_hours, console, print_log
from utils.credentials import load_credentials
from utils.kkn import KKN
from utils.logger import get_logger
from utils.simaster import Simaster

log = get_logger("group_report")

REPORT_DIR = Path(os.getenv("REPORT_DIR", "reports"))


def _build_group_summary_html(user_summaries: list[dict]) -> str:
  generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
  rows = []
  for u in user_summaries:
    status_color = "#a6e3a1" if u["status"] == "ok" else "#f38ba8"
    rows.append(
      f"<tr>"
      f"<td>{u['username']}</td>"
      f"<td>{u.get('jam_utama_sudah', 0):.1f}</td>"
      f"<td>{u.get('jam_utama_belum', 0):.1f}</td>"
      f"<td>{u.get('jam_bantu_sudah', 0):.1f}</td>"
      f"<td>{u.get('jam_bantu_belum', 0):.1f}</td>"
      f"<td>{u.get('jam_total_sudah', 0):.1f}</td>"
      f"<td>{u.get('jam_total_belum', 0):.1f}</td>"
      f"<td style='color:{status_color}'>{u['status']}</td>"
      f"<td>{u.get('error', '')}</td>"
      f"</tr>"
    )

  total_users = len(user_summaries)
  ok = [u for u in user_summaries if u["status"] == "ok"]
  total_utama_sudah = sum(u.get("jam_utama_sudah", 0) for u in ok)
  total_utama_belum = sum(u.get("jam_utama_belum", 0) for u in ok)
  total_bantu_sudah = sum(u.get("jam_bantu_sudah", 0) for u in ok)
  total_bantu_belum = sum(u.get("jam_bantu_belum", 0) for u in ok)
  total_sudah = total_utama_sudah + total_bantu_sudah
  total_belum = total_utama_belum + total_bantu_belum

  return f"""<!DOCTYPE html>
<html lang="id"><head><meta charset="utf-8">
<title>Group KKN Summary — {generated_at}</title>
<style>
  body {{ font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; margin: 2rem; color: #1e1e2e; }}
  h1 {{ color: #89dceb; border-bottom: 2px solid #89dceb; padding-bottom: .3rem; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 1rem; }}
  th, td {{ border: 1px solid #cdd6f4; padding: 0.5rem 0.7rem; text-align: left; }}
  th {{ background: #181825; color: #cdd6f4; }}
  .cards {{ display: flex; gap: 2rem; margin: 1rem 0; flex-wrap: wrap; }}
  .card {{ background: #f0f0f0; padding: 1rem 1.5rem; border-radius: 8px; }}
  .card .num {{ font-size: 1.8rem; font-weight: bold; color: #89dceb; }}
  footer {{ margin-top: 2rem; color: #6c7086; font-size: 0.8rem; }}
</style></head>
<body>
  <h1>Ringkasan Grup KKN</h1>
  <p>Dibuat: {generated_at}</p>
  <div class="cards">
    <div class="card"><div class="num">{total_users}</div>Anggota</div>
    <div class="card"><div class="num">{len(ok)}</div>Berhasil</div>
    <div class="card"><div class="num">{total_utama_sudah:.1f}</div>Jam Utama (Sudah)</div>
    <div class="card"><div class="num">{total_utama_belum:.1f}</div>Jam Utama (Belum)</div>
    <div class="card"><div class="num">{total_bantu_sudah:.1f}</div>Jam Bantu (Sudah)</div>
    <div class="card"><div class="num">{total_bantu_belum:.1f}</div>Jam Bantu (Belum)</div>
    <div class="card"><div class="num">{total_sudah:.1f}</div>Total (Sudah)</div>
    <div class="card"><div class="num">{total_belum:.1f}</div>Total (Belum)</div>
  </div>
  <h2>Per Anggota</h2>
  <table><thead><tr>
    <th>Username</th><th>Utama Sudah</th><th>Utama Belum</th><th>Bantu Sudah</th><th>Bantu Belum</th><th>Total Sudah</th><th>Total Belum</th><th>Status</th><th>Catatan</th>
  </tr></thead><tbody>{"".join(rows)}</tbody></table>
  <footer>Generated by kkn-automation</footer>
</body></html>"""


async def _process_single_user(username: str, password: str) -> dict:
  """Login as one user, fetch logbook, sum jam utama + bantu. Returns summary dict."""
  result = {
    "username": username,
    "jam_utama_sudah": 0.0, "jam_utama_belum": 0.0,
    "jam_bantu_sudah": 0.0, "jam_bantu_belum": 0.0,
    "jam_total_sudah": 0.0, "jam_total_belum": 0.0,
    "status": "ok", "error": "",
  }

  try:
    simaster = Simaster(username, password)
    session = await simaster.login(verbose=False)
    if not session:
      result["status"] = "login_failed" if not simaster.last_login_transient else "network_error"
      result["error"] = "login failed" if not simaster.last_login_transient else "network error (transient)"
      log.error("Login failed for %s (%s) — skipping", username, result["status"])
      return result

    kkn = KKN(session, simaster, autostart=False)
    await kkn._load_all(auth_provider=simaster)

    utama_all = _sum_program_hours(kkn.main_program or {})
    utama_sudah = _sum_program_hours(kkn.main_program or {}, attended_only=True)
    bantu_all = _sum_program_hours(kkn.assisted_program or {})
    bantu_sudah = _sum_program_hours(kkn.assisted_program or {}, attended_only=True)
    result["jam_utama_sudah"] = round(utama_sudah, 1)
    result["jam_utama_belum"] = round(utama_all - utama_sudah, 1)
    result["jam_bantu_sudah"] = round(bantu_sudah, 1)
    result["jam_bantu_belum"] = round(bantu_all - bantu_sudah, 1)
    result["jam_total_sudah"] = round(utama_sudah + bantu_sudah, 1)
    result["jam_total_belum"] = round((utama_all - utama_sudah) + (bantu_all - bantu_sudah), 1)

    await session.aclose()
    log.info(
      "Hours for %s: utama sudah=%.1f belum=%.1f | bantu sudah=%.1f belum=%.1f",
      username, utama_sudah, utama_all - utama_sudah, bantu_sudah, bantu_all - bantu_sudah,
    )
    return result

  except Exception as e:
    result["status"] = "error"
    result["error"] = str(e)
    log.error("Failed to process %s: %s", username, e, exc_info=True)
    return result


async def show_group_hours() -> bool:
  """Login as every credential, display jam utama + bantu table. No file export."""
  creds = load_credentials()
  if not creds:
    print_log("No credentials found — set SIMASTER_CREDENTIALS or credentials.json", "ERROR")
    return False

  log.info("Fetching hours for %d users", len(creds))

  summaries = []
  for username, password in creds.items():
    print(f"Fetching {username}...")
    summary = await _process_single_user(username, password)
    summaries.append(summary)

  table = Table(box=None, title="Jam Proker Semua Anggota")
  table.add_column("User")
  table.add_column("Jam Utama (Sudah)", justify="right")
  table.add_column("Jam Utama (Belum)", justify="right")
  table.add_column("Jam Bantu (Sudah)", justify="right")
  table.add_column("Jam Bantu (Belum)", justify="right")
  table.add_column("Total (Sudah)", justify="right", style="bold #a6e3a1")
  table.add_column("Total (Belum)", justify="right", style="bold #f38ba8")
  table.add_column("Status")
  for s in summaries:
    table.add_row(
      s["username"],
      f"{s.get('jam_utama_sudah', 0):.1f}",
      f"{s.get('jam_utama_belum', 0):.1f}",
      f"{s.get('jam_bantu_sudah', 0):.1f}",
      f"{s.get('jam_bantu_belum', 0):.1f}",
      f"{s.get('jam_total_sudah', 0):.1f}",
      f"{s.get('jam_total_belum', 0):.1f}",
      s["status"],
    )

  ok = [s for s in summaries if s["status"] == "ok"]
  table.add_section()
  table.add_row(
    "[bold]TOTAL[/]",
    f"[bold]{sum(s.get('jam_utama_sudah', 0) for s in ok):.1f}[/]",
    f"[bold]{sum(s.get('jam_utama_belum', 0) for s in ok):.1f}[/]",
    f"[bold]{sum(s.get('jam_bantu_sudah', 0) for s in ok):.1f}[/]",
    f"[bold]{sum(s.get('jam_bantu_belum', 0) for s in ok):.1f}[/]",
    f"[bold]{sum(s.get('jam_total_sudah', 0) for s in ok):.1f}[/]",
    f"[bold]{sum(s.get('jam_total_belum', 0) for s in ok):.1f}[/]",
    "",
  )

  console.print(table)

  hard_failures = [s for s in summaries if s["status"] not in ("ok", "network_error")]
  all_ok = len(hard_failures) == 0
  print_log(
    f"Done: {sum(1 for s in summaries if s['status'] == 'ok')}/{len(summaries)} users OK",
    "SUCCESS" if all_ok else "WARN",
  )
  return all_ok


async def generate_group_reports() -> bool:
  """Generate per-user reports for all SIMASTER_CREDENTIALS + group summary + Drive upload."""
  creds = load_credentials()
  if not creds:
    print_log("No credentials found — cannot generate group report", "ERROR")
    return False

  date_str = datetime.now().strftime("%Y-%m-%d")
  log.info("Starting group report for %d users", len(creds))

  summaries = []
  for username, password in creds.items():
    print(f"Processing {username}...")
    summary = await _process_single_user(username, password)
    summaries.append(summary)

  # Group summary PDF
  group_dir = REPORT_DIR / "group-summary"
  group_dir.mkdir(parents=True, exist_ok=True)
  group_html = _build_group_summary_html(summaries)
  group_html_path = group_dir / f"{date_str}-group-summary.html"
  group_pdf_path = group_dir / f"{date_str}-group-summary.pdf"

  try:
    with open(group_html_path, "w", encoding="utf-8") as f:
      f.write(group_html)
    from weasyprint import HTML as WeasyHTML

    WeasyHTML(string=group_html).write_pdf(str(group_pdf_path))
    log.info("Group summary written to %s", group_pdf_path)
  except Exception as e:
    log.error("Failed to write group summary: %s", e, exc_info=True)

  # Write group-result.json
  group_result_path = REPORT_DIR / "group-result.json"
  try:
    with open(group_result_path, "w", encoding="utf-8") as f:
      json.dump({"generated_at": datetime.now().isoformat(), "users": summaries}, f, indent=2, ensure_ascii=False)
  except Exception as e:
    log.error("Failed to write group-result.json: %s", e)

  # Print summary table
  table = Table(box=None, title="Group Report Summary")
  table.add_column("User")
  table.add_column("Utama Sudah", justify="right")
  table.add_column("Utama Belum", justify="right")
  table.add_column("Bantu Sudah", justify="right")
  table.add_column("Bantu Belum", justify="right")
  table.add_column("Total Sudah", justify="right")
  table.add_column("Total Belum", justify="right")
  table.add_column("Status")
  for s in summaries:
    table.add_row(
      s["username"],
      f"{s.get('jam_utama_sudah', 0):.1f}",
      f"{s.get('jam_utama_belum', 0):.1f}",
      f"{s.get('jam_bantu_sudah', 0):.1f}",
      f"{s.get('jam_bantu_belum', 0):.1f}",
      f"{s.get('jam_total_sudah', 0):.1f}",
      f"{s.get('jam_total_belum', 0):.1f}",
      s["status"],
    )
  console.print(table)

  # Drive upload
  if os.getenv("GDRIVE_FOLDER_ID") and os.getenv("GDRIVE_SERVICE_ACCOUNT_JSON"):
    from utils.drive import upload_directory

    for s in summaries:
      if s["status"] != "ok":
        continue
      user_dir = REPORT_DIR / s["username"] / date_str
      if user_dir.exists():
        upload_directory(user_dir, [s["username"], date_str])
    group_dir_path = REPORT_DIR / "group-summary"
    if group_dir_path.exists():
      upload_directory(group_dir_path, ["group-summary"])
  else:
    log.info("Drive not configured — reports kept locally in %s", REPORT_DIR)

  hard_failures = [s for s in summaries if s["status"] not in ("ok", "network_error")]
  all_ok = len(hard_failures) == 0
  print_log(
    f"Group report done: {sum(1 for s in summaries if s['status'] == 'ok')}/{len(summaries)} users OK",
    "SUCCESS" if all_ok else "WARN",
  )
  return all_ok
